# Generated by Django 5.1.1 on 2024-10-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='eventlocation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
