# Generated by Django 5.1.1 on 2024-10-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_eventlocation_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='organizer_id',
        ),
        migrations.RenameField(
            model_name='eventlocation',
            old_name='event',
            new_name='event_id',
        ),
    ]
