# Generated by Django 5.1.1 on 2024-11-13 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_event_event_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlocation',
            old_name='location',
            new_name='location_id',
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_name', to='events.event'),
        ),
    ]
