# Generated by Django 5.1.1 on 2024-10-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_organizer_event_organizer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer_id',
            new_name='organizer',
        ),
    ]
