# Generated by Django 5.1.1 on 2024-11-12 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('food', '0001_initial'),
        ('ngos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claim_id', models.AutoField(primary_key=True, serialize=False)),
                ('claim_status', models.CharField(max_length=50)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.fooddetail')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngos.ngo')),
            ],
        ),
    ]
